spring:
  application:
    name: "ms-configserver"
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/LeonardoPereiraBraga/ConfigServer-Biblioteca.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          username: ${GIT_USERNAME}
          password: ${GIT_TOKEN}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8071
